# Generated by Django 4.2.7 on 2024-03-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="MyModel",),
    ]
